// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2LpzQfTiJhjmMbuWGcmahqbMuV2d9yw',
    appId: '1:912675631690:web:d183f3e7fbe62cb1df2cb3',
    messagingSenderId: '912675631690',
    projectId: 'twinmart-17d93',
    authDomain: 'twinmart-17d93.firebaseapp.com',
    storageBucket: 'twinmart-17d93.firebasestorage.app',
    measurementId: 'G-TPGRSCNVZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdB7BVurxp2gFD-NHXOnrzKI5pwZCJo-g',
    appId: '1:912675631690:android:00e53d1f05d01599df2cb3',
    messagingSenderId: '912675631690',
    projectId: 'twinmart-17d93',
    storageBucket: 'twinmart-17d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF7jdMYYQQxRQBNJ3UeeLO_am3XbPuVXU',
    appId: '1:912675631690:ios:c0a37bc0a4988eb1df2cb3',
    messagingSenderId: '912675631690',
    projectId: 'twinmart-17d93',
    storageBucket: 'twinmart-17d93.firebasestorage.app',
    iosBundleId: 'com.example.twinmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF7jdMYYQQxRQBNJ3UeeLO_am3XbPuVXU',
    appId: '1:912675631690:ios:c0a37bc0a4988eb1df2cb3',
    messagingSenderId: '912675631690',
    projectId: 'twinmart-17d93',
    storageBucket: 'twinmart-17d93.firebasestorage.app',
    iosBundleId: 'com.example.twinmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX2LpzQfTiJhjmMbuWGcmahqbMuV2d9yw',
    appId: '1:912675631690:web:6a21bd556258b0c8df2cb3',
    messagingSenderId: '912675631690',
    projectId: 'twinmart-17d93',
    authDomain: 'twinmart-17d93.firebaseapp.com',
    storageBucket: 'twinmart-17d93.firebasestorage.app',
    measurementId: 'G-FEDENNRM0B',
  );
}
